# golangci-lint v2 configuration for Terraform Provider
version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused

  settings:
    govet:
      enable:
        - shadow

    misspell:
      locale: US

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/lukaspustina/terraform-provider-pihole

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

    - text: "Error return value.*Encode.*is not checked"
      linters:
        - errcheck

  exclude:
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked

  max-issues-per-linter: 10
  max-same-issues: 3
