repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: go-fmt
        entry: gofmt
        language: system
        args: [-w]
        files: \.go$
        
      - id: go-imports
        name: go-imports
        entry: goimports
        language: system
        args: [-w]
        files: \.go$
        
      - id: go-vet
        name: go-vet
        entry: go
        language: system
        args: [vet, ./...]
        files: \.go$
        pass_filenames: false
        
      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint
        language: system
        args: [run, --config, .golangci.yml]
        files: \.go$
        pass_filenames: false